Countries page view - week 2
Mustafa-Irshaid/Where-In-The-World--Project pull request #1
Opened 2023-06-30 19:55 UTC by Mustafa-Irshaid

2023-07-05 14:50 UTC, wasef89 requested changes

2023-07-05 14:50 UTC, wasef89 commented on assets/css/card-details.css
> +main{
Code not formated

2023-07-05 14:50 UTC, wasef89 commented on assets/css/card-details.css
> +.anchor--backward-routing{
back-button  isn't it better name ?

2023-07-05 14:50 UTC, wasef89 commented on assets/css/card-details.css
> +.routers-shadow{
links- shadow a better name ?

2023-07-05 14:50 UTC, wasef89 commented on assets/css/card-details.css
> +    color:var(--VeryLightGrey);
verylightGrey , veryVeryLightGray,

2023-07-05 14:50 UTC, wasef89 commented on assets/css/card-details.css
> +    height: 350px !important;
check why you need important

2023-07-05 14:50 UTC, wasef89 commented on assets/css/card-details.css
> +    height: 350px !important;
try a div with background image

2023-07-05 14:50 UTC, wasef89 commented on assets/css/header.css
> +}
naming convention clearly shows that this is wrong

2023-07-05 14:50 UTC, wasef89 commented on assets/css/filter-form.css
> +        width:50% !important;
use bootstrap instead

2023-07-05 14:50 UTC, wasef89 commented on index.html
> +                        </div>
layout has to be controlled through bootstrap

2023-07-08 15:28 UTC, Mustafa-Irshaid commented on assets/css/card-details.css
> +    height: 350px !important;
@wasef89 

1- It turned out no need for !important in this matter

2- After I've tried a div with a background its possible but turned out I'am getting the same result which is not bad

I've searched about "_which better to use image as background with CSS or as an element with HTML ?_" and the answer was we only use CSS images only for decorative purposes , Since the image serves an informational function.
I see that its better to use the image as HTML element

2023-07-12 10:16 UTC, merged